/////////////AUTHENTICATE actions////////////
export const AUTHENTICATE = "AUTHENTICATE";
/////////////////loader action///////////////
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

/////////////GET ALL PRODUCTSS 
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

///////////////PRODUCTS DETAILS
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
export const CART_ADD_ITEM ="CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";